# The version of the docker-compose.
version: "3.8"

volumes:
  backend_node_modules:
  frontend_node_modules:
# Telling docker-compose to build the client and server images and run them in containers.
services:
  frontend:
    # Telling docker-compose to build the client image using the Dockerfile in the client directory.
    build: ./frontend
    # Giving the container a name.
    container_name: frontend_c
    # Mapping the port 3000 on the host machine to the port 3000 on the container.
    ports:
      - "3000:3000"
    # Mapping the client directory on the host machine to the /app directory on the container.
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    # Allows you to run container in detached mode.
    stdin_open: true
    tty: true
  backend:
    # Telling docker-compose to build the client image using the Dockerfile in the server directory.
    build: ./backend
    container_name: backend_c
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
